# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{im_magick}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fabien Franzen"]
  s.date = %q{2011-01-20}
  s.description = %q{}
  s.email = %q{info@atelierfabien.be}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "History.txt",
    "License.txt",
    "Manifest.txt",
    "README",
    "Rakefile",
    "lib/im_magick.rb",
    "lib/im_magick/command/base.rb",
    "lib/im_magick/command/collector.rb",
    "lib/im_magick/command/composite.rb",
    "lib/im_magick/command/convert.rb",
    "lib/im_magick/command/emitter.rb",
    "lib/im_magick/command/identify.rb",
    "lib/im_magick/command/mogrify.rb",
    "lib/im_magick/command/montage.rb",
    "lib/im_magick/command/runner.rb",
    "lib/im_magick/core_ext/class.rb",
    "lib/im_magick/core_ext/hash.rb",
    "lib/im_magick/core_ext/string.rb",
    "lib/im_magick/image.rb",
    "lib/im_magick/image_info.rb",
    "lib/im_magick/image_macros.rb",
    "lib/im_magick/merbtasks.rb",
    "lib/im_magick/util/geometry.rb",
    "lib/im_magick/util/temp_file.rb",
    "lib/im_magick/version.rb",
    "spec/fixtures/ImageMagick.jpg",
    "spec/fonts/union.ttf",
    "spec/fonts/unionbd.ttf",
    "spec/im_magick_convert_spec.rb",
    "spec/im_magick_image_info_spec.rb",
    "spec/im_magick_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/fabien/im_magick}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An alternative to RMagick which uses *magick directly from the shell}
  s.test_files = [
    "spec/im_magick_convert_spec.rb",
    "spec/im_magick_image_info_spec.rb",
    "spec/im_magick_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

